import re

# codes used by CorCenCC transcribers to document non-lexical features of speech
transcriber_codes = ["<saib>", "<=>", "</=>", "</==>", "<aneglur>", "< aneglur>", "<aneglur?>", "< aneglur?>", "<anelgur>", "<saib>", "<->", "<anadlu>", "<clecian gwefusau>", "<clirio gwddf>", "<cnoi>", "<cusanu>", "<chwerthin>", "<chwibanu>", "<chwyrnu>", "<chwythu allan yn sydyn>", "<chwythu trwyn>", "<dyheu>", "<dylyfu gên>", "<dylyfu gen>", "<ebychu>", "<giglan>", "<griddfan>", "<gwichian>", "<hisian>", "<hymian>", "<llefain>", "<ocheneidio>", "<ochneidio>", "<ochenaid>", "<pesychu>", "<peswch>", "<sgrechian>", "<slochian>", "<sniffian>", "<swnian>", "<tagu>", "<tisian>", "<torri gwynt>", "<traflyncu>", "<wfftio>", "<canu>", "<ailadrodd>", "<anadlu allan yn drwm>", "<anadlu allan yn sydyn>", "<anadlu allan>", "<anadlu mewn>", "<lleferydd di-gymraeg>", "</saib>"]

two_mut = {"bo", "bu", "ca", "ci", "co", "da", "da", "da", "de", "de", "de", "du", "go", "ia", "ol", "os", "pa", "pa", "pa", "pe", "pi", "pw", "ta", "ta", "te", "te", "ti", "to", "to", "to", "to", "tu", "ty", "tŷ", "un", "wy", "yd", "ôl", "ŵy", "ŷd"}

""" The morphological elements that make up each rich POS tag """
morphological_table = {"Egu": {"cat":"E", "gender":"g", "number":"u"},
                        "Ebu": {"cat":"E", "gender": "b", "number": "u"},
                        "Egll": {"cat":"E", "gender": "g", "number": "ll"},
                        "Ebll": {"cat":"E", "gender": "b", "number": "ll"},
                        "Egbu": {"cat":"E", "gender": "gb", "number": "u"},
                        "Egbll": {"cat":"E", "gender": "gb", "number": "ll"},
                        "Ep": {"cat":"E", "prop":"p"},
                        "Epg": {"cat":"E", "prop": "p", "gender":"g"},
                        "Epb": {"cat":"E", "prop": "p", "gender":"b"},
                        "Arsym": {"cat":"Ar", "prep_type":"sym"},
                        "Ar1u": {"cat":"Ar", "person":"1", "number": "u"},
                        "Ar2u": {"cat":"Ar", "person":"2", "number": "u"},
                        "Ar3gu": {"cat":"Ar", "person":"3", "gender": "g", "number": "u"},
                        "Ar3bu": {"cat":"Ar", "person":"3", "gender": "b", "number": "u"},
                        "Ar1ll": {"cat":"Ar", "person":"1", "number": "ll"},
                        "Ar2ll": {"cat":"Ar", "person":"2", "number": "ll"},
                        "Ar3ll": {"cat":"Ar", "person":"3", "number": "ll"},
                        "Cyscyd": {"cat":"Cys", "status": "cyd"},
                        "Cysis": {"cat":"Cys", "status": "is"},
                        "Rhifol": {"cat":"Rhi", "num_type":"fol"},
                        "Rhifold": {"cat":"Rhi", "num_type":"fol", "decimal":"d"},
                        "Rhifolt": {"cat":"Rhi", "num_type":"fol", "decimal":"t"},
                        "Rhitref": {"cat":"Rhi", "num_type":"tref"},
                        "Rhitrefd": {"cat":"Rhi", "num_type":"tref", "decimal": "d"},
                        "Rhitreft": {"cat":"Rhi", "num_type":"tref", "decimal": "t"},
                        "Anscadu": {"cat":"Ans", "comparison": "cad", "number": "u"},
                        "Anscadbu": {"cat":"Ans", "comparison": "cad", "gender": "b", "number": "u"},
                        "Anscadll": {"cat":"Ans", "comparison": "cad", "number": "ll"},
                        "Anscadbll": {"cat":"Ans", "comparison": "cad", "gender" : "b", "number": "ll"},
                        "Anscadgll": {"cat":"Ans", "comparison": "cad", "gender" : "g", "number": "ll"},
                        "Anscyf": {"cat":"Ans", "comparison": "cyf"},
                        "Anscym": {"cat":"Ans", "comparison": "cym"},
                        "Anseith": {"cat":"Ans", "comparison": "eith"},
                        "Be": {"cat":"B", "nounlike": "e"},
                        "Bpres1u": {"cat":"B", "verb_tense":"pres", "person":"1", "number": "u"},
                        "Bpres2u": {"cat":"B", "verb_tense":"pres", "person":"2", "number": "u"},
                        "Bpres3u": {"cat":"B", "verb_tense":"pres", "person":"3", "number": "u"},
                        "Bpres1ll": {"cat":"B", "verb_tense":"pres", "person":"1", "number": "ll"},
                        "Bpres2ll": {"cat":"B", "verb_tense":"pres", "person":"2", "number": "ll"},
                        "Bpres3ll": {"cat":"B", "verb_tense":"pres", "person":"3", "number": "ll"},
                        "Bpresamhers": {"cat":"B", "verb_tense":"pres", "verb_type":"amhers"},
                        "Bpres3perth": {"cat":"B", "verb_tense":"pres", "person":"3", "verb_type":"perth"},
                        "Bpres3amhen": {"cat":"B", "verb_tense":"pres", "person":"3", "verb_type":"amhen"},
                        "Bdyf1u": {"cat":"B", "verb_tense":"dyf", "person":"1", "number": "u"},
                        "Bdyf2u": {"cat":"B", "verb_tense":"dyf", "person":"2", "number": "u"},
                        "Bdyf3u": {"cat":"B", "verb_tense":"dyf", "person":"3", "number": "u"},
                        "Bdyf1ll": {"cat":"B", "verb_tense":"dyf", "person":"1", "number": "ll"},
                        "Bdyf2ll": {"cat":"B", "verb_tense":"dyf", "person":"2", "number": "ll"},
                        "Bdyf3ll": {"cat":"B", "verb_tense":"dyf", "person":"3", "number": "ll"},
                        "Bdyfamhers": {"cat":"B", "verb_tense":"dyf", "verb_type":"amhers"},
                        "Bgorb1u": {"cat":"B", "verb_tense":"gorb", "person":"1", "number": "u"},
                        "Bgorb2u": {"cat":"B", "verb_tense":"gorb", "person":"2", "number": "u"},
                        "Bgorb3u": {"cat":"B", "verb_tense":"gorb", "person":"3", "number": "u"},
                        "Bgorb1ll": {"cat":"B", "verb_tense":"gorb", "person":"1", "number": "ll"},
                        "Bgorb2ll": {"cat":"B", "verb_tense":"gorb", "person":"2", "number": "ll"},
                        "Bgorb3ll": {"cat":"B", "verb_tense":"gorb", "person":"3", "number": "ll"},
                        "Bgorbamhers": {"cat":"B", "verb_tense":"gorb", "verb_type":"amhers"},
                        "Bamherff1u": {"cat":"B", "verb_tense":"amherff", "person":"1", "number": "u"},
                        "Bamherff2u": {"cat":"B", "verb_tense":"amherff", "person":"2", "number": "u"},
                        "Bamherff3u": {"cat":"B", "verb_tense":"amherff", "person":"3", "number": "u"},
                        "Bamherff1ll": {"cat":"B", "verb_tense":"amherff", "person":"1", "number": "ll"},
                        "Bamherff2ll": {"cat":"B", "verb_tense":"amherff", "person":"2", "number": "ll"},
                        "Bamherff3ll": {"cat":"B", "verb_tense":"amherff", "person":"3", "number": "ll"},
                        "Bamherffamhers": {"cat":"B", "verb_tense":"amherff", "verb_type":"amhers"},
                        "Bgorff1u": {"cat":"B", "verb_tense":"gorff", "person":"1", "number": "u"},
                        "Bgorff2u": {"cat":"B", "verb_tense":"gorff", "person":"2", "number": "u"},
                        "Bgorff3u": {"cat":"B", "verb_tense":"gorff", "person":"3", "number": "u"},
                        "Bgorff1ll": {"cat":"B", "verb_tense":"gorff", "person":"1", "number": "ll"},
                        "Bgorff2ll": {"cat":"B", "verb_tense":"gorff", "person":"2", "number": "ll"},
                        "Bgorff3ll": {"cat":"B", "verb_tense":"gorff", "person":"3", "number": "ll"},
                        "Bgorffamhers": {"cat":"B", "verb_tense":"gorff", "verb_type":"amhers"},
                        "Bgorffsef": {"cat":"B", "verb_tense":"gorff", "variance": "sef"},
                        "Bgorch2u": {"cat":"B", "verb_tense":"gorch", "person":"2", "number": "u"},
                        "Bgorch3u": {"cat":"B", "verb_tense":"gorch", "person":"3", "number": "u"},
                        "Bgorch1ll": {"cat":"B", "verb_tense":"gorch", "person":"1", "number": "ll"},
                        "Bgorch2ll": {"cat":"B", "verb_tense":"gorch", "person":"2", "number": "ll"},
                        "Bgorch3ll": {"cat":"B", "verb_tense":"gorch", "person":"3", "number": "ll"},
                        "Bgorchamhers": {"cat":"B", "verb_tense":"gorch", "verb_type":"amhers"},
                        "Bdibdyf1u": {"cat":"B", "verb_tense":"dibdyf", "person":"1", "number": "u"},
                        "Bdibdyf2u": {"cat":"B", "verb_tense":"dibdyf", "person":"2", "number": "u"},
                        "Bdibdyf3u": {"cat":"B", "verb_tense":"dibdyf", "person":"3", "number": "u"},
                        "Bdibdyf1ll": {"cat":"B", "verb_tense":"dibdyf", "person":"1", "number": "ll"},
                        "Bdibdyf2ll": {"cat":"B", "verb_tense":"dibdyf", "person":"2", "number": "ll"},
                        "Bdibdyf3ll": {"cat":"B", "verb_tense":"dibdyf", "person":"3", "number": "ll"},
                        "Bdibdyfamhers": {"cat":"B", "verb_tense":"dibdyf", "verb_type":"amhers"},
                        "Bamod1u": {"cat":"B", "verb_tense":"amod", "person":"1", "number": "u"},
                        "Bamod2u": {"cat":"B", "verb_tense":"amod", "person":"2", "number": "u"},
                        "Bamod3u": {"cat":"B", "verb_tense":"amod", "person":"3", "number": "u"},
                        "Bamod1ll": {"cat":"B", "verb_tense":"amod", "person":"1", "number": "ll"},
                        "Bamod2ll": {"cat":"B", "verb_tense":"amod", "person":"2", "number": "ll"},
                        "Bamod3ll": {"cat":"B", "verb_tense":"amod", "person":"3", "number": "ll"},
                        "Bamodamhers": {"cat":"B", "verb_tense":"amod", "verb_type":"amhers"},
                        "Rhapers1u": {"cat":"Rha", "personal":"pers", "person":"1", "number": "u"},
                        "Rhapers2u": {"cat":"Rha", "personal":"pers", "person":"2", "number": "u"},
                        "Rhapers3gu": {"cat":"Rha", "personal":"pers", "person":"3", "gender": "g", "number": "u"},
                        "Rhapers3bu": {"cat":"Rha", "personal":"pers", "person":"3", "gender": "b", "number": "u"},
                        "Rhapers3du": {"cat":"Rha", "personal":"pers", "person":"3", "gender": "d", "number": "u"},
                        "Rhapers1ll": {"cat":"Rha", "personal":"pers", "person":"1", "number": "ll"},
                        "Rhapers2ll": {"cat":"Rha", "personal":"pers", "person":"2", "number": "ll"},
                        "Rhapers3ll": {"cat":"Rha", "personal":"pers", "person":"3", "number": "ll"},
                        "Rhadib1u": {"cat":"Rha", "pron_type":"dib", "person":"1", "number": "u"},
                        "Rhadib2u": {"cat":"Rha", "pron_type":"dib", "person":"2", "number": "u"},
                        "Rhadib3gu": {"cat":"Rha", "pron_type":"dib", "person":"3", "gender": "g", "number": "u"},
                        "Rhadib3bu": {"cat":"Rha", "pron_type":"dib", "person":"3", "gender": "b", "number": "u"},
                        "Rhadib1ll": {"cat":"Rha", "pron_type":"dib", "person":"1", "number": "ll"},
                        "Rhadib2ll": {"cat":"Rha", "pron_type":"dib", "person":"2", "number": "ll"},
                        "Rhadib3ll": {"cat":"Rha", "pron_type":"dib", "person":"3", "number": "ll"},
                        "Rhamedd1u": {"cat":"Rha", "pron_type":"medd", "person":"1", "number": "u"},
                        "Rhamedd2u": {"cat":"Rha", "pron_type":"medd", "person":"2", "number": "u"},
                        "Rhamedd3gu": {"cat":"Rha", "pron_type":"medd", "person":"3", "gender": "g", "number": "u"},
                        "Rhamedd3bu": {"cat":"Rha", "pron_type":"medd", "person":"3", "gender": "b", "number": "u"},
                        "Rhamedd1ll": {"cat":"Rha", "pron_type":"medd", "person":"1", "number": "ll"},
                        "Rhamedd2ll": {"cat":"Rha", "pron_type":"medd", "person":"2", "number": "ll"},
                        "Rhamedd3ll": {"cat":"Rha", "pron_type":"medd", "person":"3", "number": "ll"},
                        "Rhacys1u": {"cat":"Rha", "pron_type":"cys", "person":"1", "number": "u"},
                        "Rhacys2u": {"cat":"Rha", "pron_type":"cys", "person":"2", "number": "u"},
                        "Rhacys3gu": {"cat":"Rha", "pron_type":"cys", "person":"3", "gender": "g", "number": "u"},
                        "Rhacys3bu": {"cat":"Rha", "pron_type":"cys", "person":"3", "gender": "b", "number": "u"},
                        "Rhacys1ll": {"cat":"Rha", "pron_type":"cys", "person":"1", "number": "ll"},
                        "Rhacys2ll": {"cat":"Rha", "pron_type":"cys", "person":"2", "number": "ll"},
                        "Rhacys3ll": {"cat":"Rha", "pron_type":"cys", "person":"3", "number": "ll"},
                        "Rhagof": {"cat":"Rha", "pron_type":"gof"},
                        "Rhadangg": {"cat":"Rha", "pron_type":"dang", "gender":"g"},
                        "Rhadangb": {"cat":"Rha", "pron_type":"dang", "gender":"b"},
                        "Rhadangd": {"cat":"Rha", "pron_type":"dang", "gender":"d"},
                        "Rhadang": {"cat":"Rha", "pron_type":"dang"},
                        "Rhadangll": {"cat":"Rha", "pron_type":"dang", "number": "ll"},
                        "Rhaperth": {"cat":"Rha", "pron_type":"perth"},
                        "Rhaatb": {"cat":"Rha", "pron_type":"atb"},
                        "Rhaamh": {"cat":"Rha", "pron_type":"amh"},
                        "Rhacil": {"cat":"Rha", "pron_type":"cil"},
                        "Uneg": {"cat":"U", "particle_type":"neg"},
                        "Ucad": {"cat":"U", "particle_type":"cad"},
                        "Ugof": {"cat":"U", "particle_type":"gof"},
                        "Utra": {"cat":"U", "particle_type":"tra"},
                        "Urhagf": {"cat":"U", "particle_type":"rhagf"},
                        "Uberf": {"cat":"U", "particle_type":"berf"},
            # Ublaen: Blaenddodiaid - prefixes
                        "Ublaen": {"cat":"U", "particle_type":"blaen"},
                        "Gwest": {"cat":"Gw", "other_type":"est"},
                        "Gwfform": {"cat":"Gw", "other_type":"fform"},
                        "Gwsym": {"cat":"Gw", "other_type":"sym"},
                        "Gwacr": {"cat":"Gw", "other_type":"acr"},
                        "Gwtalf": {"cat":"Gw", "other_type":"talf"},
                        "Gwdig": {"cat":"Gw", "other_type":"dig"},
                        "Gwllyth": {"cat":"Gw", "other_type":"llyth"},
                        "Gwann": {"cat":"Gw", "other_type":"ann"},
                        "Atdt": {"cat":"Atd", "punct_type":"t"},
                        "Atdcan": {"cat":"Atd", "punct_type":"can"},
                        "Atdchw": {"cat":"Atd", "punct_type":"chw"},
                        "Atdde": {"cat":"Atd", "punct_type":"de"},
                        "Atdcys": {"cat":"Atd", "punct_type":"cys"},
                        "Atddyf": {"cat":"Atd", "punct_type":"dyf"},
                        "Bansym": {"cat":"Ban", "det_type":"sym"},
                        "Banamh": {"cat":"Ban", "det_type":"amh"},
                        "Banmeint": {"cat":"Ban", "det_type":"meint"},
                        "Bancynnar": {"cat":"Ban", "det_type":"cynnar"},
                    ### Bancynnar = what Borsley et al (Syntax of Welsh) call "early postdeterminers"
                        "Banhwyr": {"cat":"Ban", "det_type":"hwyr"},
                    ### Banhwyr = what Borsley et al (Syntax of Welsh) call "late postdeterminers"
                        "Bandangb": {"cat":"Ban", "det_type":"dang", "gender":"b"},
                        "Bandangg": {"cat":"Ban", "det_type":"dang", "gender":"g"},
                        "Bandangd": {"cat":"Ban", "det_type":"dang", "gender":"d"},
                        "Bandang": {"cat":"Ban", "det_type":"dang"},
                    ### Bandang = demonstrative determiner
                        "Bangof": {"cat":"Ban", "det_type":"gof"},
                    ### Bangof = interrogative determiner "pa": "pa lyfr?"
                        "Banmedd": {"cat":"Ban", "det_type":"medd"},
                        "Banmedd1ll": {"cat":"Ban", "det_type":"medd", "person":"1", "number": "ll"},
                        "Banmedd1u": {"cat":"Ban", "det_type":"medd", "person":"1", "number": "u"},
                        "Banmedd2ll": {"cat":"Ban", "det_type":"medd", "person":"2", "number": "ll"},
                        "Banmedd2u": {"cat":"Ban", "det_type":"medd", "person":"2", "number": "u"},
                        "Banmedd3bu": {"cat":"Ban", "det_type":"medd", "person":"3", "gender": "b", "number": "u"},
                        "Banmedd3gu": {"cat":"Ban", "det_type":"medd", "person":"3", "gender": "g", "number": "u"},
                        "Banmedd3du": {"cat":"Ban", "det_type":"medd", "person":"3", "gender":"d", "number": "u"},
                        "Banmedd3ll": {"cat":"Ban", "det_type":"medd", "person":"3", "number": "ll"},
                        "Adf": {"cat": "Adf"},
                        "YFB": {"cat": "YFB"},
                        "Ebych": {"cat": "Ebych"},

                    ### Ymadrodd - a tag for lemmas representing more than one part of speech, e.g. "'s'na'm" - "does yna ddim" (= "there is/are not")
                        "Ymadr": {"cat":"Ymadr"},
                    ### Anon - a tag for Anonymized data: the contents of <anon> tags in the CorCenCC data may range from a telephone number to a single name to a complete name (title + given name + surname) to an entire address, so part of speech is not easy to assign
                        "Anon":{"cat":"Anon"},
                    ### Experimental categories for English words
                        "Bsym": {"cat":"B", "verb_tense":"sym"},
                        "Bing": {"cat":"B", "verb_tense":"ing"},
                        "Ben": {"cat":"B", "verb_tense":"en"},
                        "Bannherf": {"cat":"B", "verb_tense":"annherf"},
                        "Bgynfodd": {"cat":"B", "verb_tense":"gynfodd"},
                        "Bgorff": {"cat":"B", "verb_tense":"gorff"},
                        "Bpres": {"cat":"B", "verb_tense":"pres"},
                        "Bpresll": {"cat":"B", "verb_tense":"pres", "number":"ll"},
                        "Eu": {"cat":"E", "number":"u"},
                        "Edr": {"cat":"E", "number":"dr"},
                        "Ell": {"cat":"E", "number":"ll"},
                        "Epll": {"cat":"E", "prop":"p", "number":"ll"},
                        "Epu": {"cat":"E", "prop":"p", "number":"u"},
                        "Arof": {"cat":"Ar", "prep_type":"of"},
                        "Arcym": {"cat":"Ar", "prep_type":"cym"},
                        "Anscad": {"cat":"Ans", "comparison":"cad"},
                        "Uadf": {"cat":"U", "particle_type":"adf"},
                        "Umedd": {"cat":"U", "particle_type":"medd"},
                        "Uannherf": {"cat":"U", "particle_type":"annherf"},
                        "Udirf": {"cat":"U", "particle_type":"dirf"}
                        }

html_tags = {"a","abbr","acronym","address","applet","area","article","aside","audio","b","base","basefont","bdi","bdo","big","blockquote","body","br","button","canvas","caption","center","cite","code","col","colgroup","data","datalist","dd","del","details","dfn","dialog","dir","div","dl","dt","em","embed","fieldset","figcaption","figure","font","footer","form","frame","frameset","head","header","hgroup","h1","h2","h3","h4","h5","h6","h7","hr","html","i","iframe","img","input","ins","kbd","keygen","label","legend","li","link","main","map","mark","menu","menuitem","meta","meter","nav","noframes","noscript","object","ol","optgroup","option","output","p","param","picture","pre","progress","q","rp","rt","ruby","s","samp","script","section","select","small","source","span","strike","strong","style","sub","summary","sup","svg","table","tbody","td","template","textarea","tfoot","th","thead","time","title","tr","track","tt","u","ul","var","video","wbr","br/", "hr/", "br /", "hr /"}

diw_cym = {"a" : ["Bgorch2u", "Bpres3u"],
"af" : ["Bpres1u", "Anseith"],
"ai" : ["Bamherff3u", "Ell"], 
"ais" : ["Bgorff1u", "Bgorff2u"],
"aist" : ["Bgorff2u"], 
"an" : ["Bpres3ll"], 
"ant" : ["Bpres3ll"], 
"asai" : ["Bgorb3u"], 
"asant" : ["Bgorff3ll"], 
"asech" : ["Bgorb2ll"], 
"asem" : ["Bgorb1ll"], 
"asen" : ["Bgorb3ll"], 
"asent" : ["Bgorb3ll"], 
"asid" : ["Bgorbamhers"], 
"asit" : ["Bgorb2u"], 
"asoch" : ["Bgorff2ll"], 
"asom" : ["Bgorff1ll"], 
"aswn" : ["Bgorb1u"], 
"ia" : ["Bgorch2u", "Bpres3u"],
"iaf" : ["Bpres1u", "Anseith"],
"iai" : ["Bamherff3u", "Ell"], 
"iais" : ["Bgorff1u", "Bgorff2u"],
"iaist" : ["Bgorff2u"], 
"ian" : ["Bpres3ll"], 
"iant" : ["Bpres3ll"], 
"iasai" : ["Bgorb3u"], 
"iasant" : ["Bgorff3ll"], 
"iasech" : ["Bgorb2ll"], 
"iasem" : ["Bgorb1ll"], 
"iasen" : ["Bgorb3ll"], 
"iasent" : ["Bgorb3ll"], 
"iasid" : ["Bgorbamhers"], 
"iasit" : ["Bgorb2u"], 
"iasoch" : ["Bgorff2ll"], 
"iasom" : ["Bgorff1ll"], 
"iaswn" : ["Bgorb1u"], 
"ech" : ["Bamherff2ll"], 
"ed" : ["Bgorch3u"], 
"em" : ["Bamherff1ll"], 
"en" : ["Bgorch3ll", "Eu"],
"ent" : ["Bamherff3ll", "Bgorch3ll"],
"er" : ["Bdibdyfamhers", "Bgorchamhers"],
"e" : ["Bamherff3u"], 
"es" : ["Bgorff1u", "Bgorff2u"],
"est" : ["Bgorff2u"],  
"et" : ["Bamherff2u"], 
"iech" : ["Bamherff2ll"], 
"ied" : ["Bgorch3u"], 
"iem" : ["Bamherff1ll"], 
"ien" : ["Bgorch3ll", "Eu"],
"ient" : ["Bamherff3ll", "Bgorch3ll"],
"ier" : ["Bdibdyfamhers", "Bgorchamhers"],
"ie" : ["Bamherff3u"], 
"ies" : ["Bgorff1u", "Bgorff2u"],
"iest" : ["Bgorff2u"],  
"iet" : ["Bamherff2u"], 
"i" : ["Bpres2u"], 
"ia" : ["Bgorch2u", "Bpres3u"],
"id" : ["Bamherffamhers"], 
"iff" : ["Bdyf3u"], 
"io" : ["Be"],
"ion" : ["Bgorff1ll", "Bgorff3ll", "Ell"],
"ir" : ["Bpresamhers"], 
"it" : ["Bamherff2u"], 
"ith" : ["Bdyf3u"], 
"o" : ["Be", "Bdibdyf3u"],
"och" : ["Bdibdyf2ll", "Bgorff2ll"],
"odd" : ["Bgorff3u"], 
"om" : ["Bdibdyf1ll"], 
"on" : ["Bgorff1ll", "Bgorff3ll", "Ell"],
"ont" : ["Bdibdyf3ll"],
"ioch" : ["Bdibdyf2ll", "Bgorff2ll"],
"iodd" : ["Bgorff3u"], 
"iom" : ["Bdibdyf1ll"], 
"ion" : ["Bgorff1ll", "Bgorff3ll", "Ell"],
"iont" : ["Bdibdyf3ll"],  
"soch" : ["Bgorff2ll"], 
"som" : ["Bgorff1ll"], 
"son" : ["Bgorff3ll"], 
"wch" : ["Bgorch2ll", "Bpres2ll"],
"wn" : ["Bamherff1u", "Bgorch1ll", "Bpres1ll"],
"wyd" : ["Bgorffamhers"], 
"wyf" : ["Bdibdyf1u"], 
"iwch" : ["Bgorch2ll", "Bpres2ll"],
"iwn" : ["Bamherff1u", "Bgorch1ll", "Bpres1ll"],
"iwyd" : ["Bgorffamhers"], 
"iwyf" : ["Bdibdyf1u"], 
"iych" : ["Bdibdyf2u"],
"od" : ["Ell"],
"au" : ["Ell"],
"iau" : ["Ell"],
"oedd" : ["Ell"],
"yn" : ["Eu"],
"ach" : ["Anscym"]
}

pos_enriched_keys = {'particle_type', 'gender', 'verb_tense', 'nounlike', 'decimal', 'status', 'punct_type', 'cat', 'person', 'prop', 'num_type', 'pron_type', 'number', 'personal', 'prep_type', 'verb_type', 'det_type', 'variance', 'other_type', 'comparison'}

def foreign_chars(token):
    non_welsh = 0
    for char in token:
        if ord(char) > ord('z'):
            if char not in ["â", "ê", "î", "ô", "û", "ŵ", "ŷ", "ä", "ë", "ö", "ï", "é", "è", "í", "ì", "Â", "Ê", "Î", "Ô", "Û", "Ŵ", "Ŷ", "Ä", "Ë", "Ö", "Ï", "É", "È", "Í", "Ì"]:
                non_welsh += 1
    if non_welsh > 0:
        return True

hashtag = re.compile(r"(#[a-zA-Z0-9_\-']+[a-zA-Z0-9]+)")
email = re.compile(r"([a-zA-Z0-9\.\-_]+@[a-zA-Z0-9\-\._]+\.(?:travelersinsurance|northwesternmutual|sandvikcoromant|kerryproperties|americanexpress|weatherchannel|kerrylogistics|cookingchannel|cancerresearch|bananarepublic|americanfamily|afamilycompany|wolterskluwer|travelchannel|spreadbetting|lifeinsurance|international|versicherung|scholarships|lplfinancial|construction|williamhill|redumbrella|progressive|productions|playstation|photography|olayangroup|motorcycles|lamborghini|kerryhotels|investments|foodnetwork|enterprises|engineering|creditunion|contractors|calvinklein|bridgestone|blockbuster|blackfriday|barclaycard|accountants|volkswagen|vlaanderen|university|technology|tatamotors|swiftcover|schaeffler|restaurant|republican|realestate|prudential|protection|properties|onyourside|nextdirect|newholland|nationwide|mitsubishi|management|industries|immobilien|healthcare|foundation|extraspace|eurovision|cuisinella|creditcard|consulting|capitalone|boehringer|bnpparibas|basketball|associates|apartments|accountant|yodobashi|vacations|travelers|stockholm|statefarm|statebank|solutions|shangrila|scjohnson|richardli|pramerica|passagens|panasonic|microsoft|melbourne|marshalls|marketing|lifestyle|landrover|lancaster|kuokgroup|insurance|institute|homesense|homegoods|homedepot|hisamitsu|goldpoint|furniture|fujixerox|frontdoor|fresenius|firestone|financial|fairwinds|equipment|education|directory|community|christmas|bloomberg|barcelona|aquarelle|analytics|amsterdam|allfinanz|alfaromeo|accenture|yokohama|woodside|verisign|ventures|vanguard|training|supplies|stcgroup|software|softbank|showtime|shopping|services|security|samsclub|saarland|reliance|redstone|property|plumbing|pictures|pharmacy|partners|observer|mortgage|merckmsd|memorial|mckinsey|maserati|marriott|lundbeck|lighting|jpmorgan|istanbul|ipiranga|infiniti|hospital|holdings|helsinki|hdfcbank|guardian|graphics|grainger|goodyear|frontier|football|firmdale|fidelity|feedback|exchange|etisalat|ericsson|engineer|download|discover|discount|diamonds|democrat|deloitte|delivery|computer|commbank|clothing|clinique|cleaning|cityeats|cipriani|catholic|catering|capetown|business|builders|budapest|brussels|broadway|bradesco|boutique|baseball|bargains|barefoot|barclays|attorney|allstate|airforce|abudhabi|zuerich|youtube|yamaxun|xfinity|winners|windows|whoswho|wedding|website|weather|watches|wanggou|walmart|trading|toshiba|tiffany|tickets|theatre|theater|temasek|systems|surgery|support|storage|staples|singles|shriram|shiksha|science|schwarz|schmidt|sandvik|samsung|rexroth|reviews|rentals|recipes|realtor|politie|pioneer|philips|origins|organic|oldnavy|okinawa|neustar|network|netflix|netbank|monster|markets|lincoln|limited|leclerc|latrobe|lasalle|lanxess|lacaixa|komatsu|kitchen|juniper|jewelry|ismaili|hyundai|hotmail|hoteles|hosting|holiday|hitachi|hangout|hamburg|guitars|grocery|godaddy|genting|gallery|fujitsu|frogans|forsale|flowers|florist|flights|fitness|fishing|finance|ferrero|ferrari|fashion|farmers|express|exposed|domains|digital|dentist|cruises|cricket|courses|coupons|country|corsica|cooking|contact|compare|company|comcast|cologne|college|clubmed|citadel|chintai|charity|channel|careers|caravan|capital|bugatti|brother|booking|bestbuy|bentley|bauhaus|banamex|avianca|auspost|audible|auction|athleta|android|alibaba|agakhan|academy|abogado|zappos|yandex|yachts|xihuan|webcam|walter|vuelos|voyage|voting|vision|virgin|villas|viking|viajes|unicom|travel|toyota|tkmaxx|tjmaxx|tienda|tennis|tattoo|target|taobao|taipei|sydney|swatch|suzuki|supply|studio|stream|social|soccer|shouji|select|secure|search|schule|school|sanofi|sakura|safety|ryukyu|rogers|rocher|review|report|repair|reisen|realty|racing|quebec|pictet|physio|photos|pfizer|otsuka|orange|oracle|online|olayan|office|nowruz|norton|nissay|nissan|natura|nagoya|mutual|museum|moscow|mormon|monash|mobile|mattel|market|makeup|maison|madrid|luxury|london|locker|living|lefrak|lawyer|latino|lancia|kosher|kindle|kinder|kaufen|juegos|joburg|jaguar|intuit|insure|imamat|hughes|hotels|hockey|hiphop|hermes|health|gratis|google|global|giving|george|garden|gallup|futbol|flickr|family|expert|events|estate|energy|emerck|durban|dupont|dunlop|doctor|direct|design|dental|degree|dealer|datsun|dating|cruise|credit|coupon|condos|comsec|coffee|clinic|claims|circle|church|chrome|chanel|center|casino|caseih|career|camera|broker|boston|bostik|bharti|berlin|beauty|bayern|author|aramco|anquan|amazon|alstom|alsace|alipay|airtel|airbus|agency|africa|abbvie|abbott|abarth|yahoo|xerox|world|works|weibo|weber|watch|wales|volvo|vodka|video|vegas|ubank|tushu|tunes|trust|trade|tours|total|toray|tools|tokyo|today|tmall|tirol|tires|tatar|swiss|sucks|style|study|store|stada|sport|space|solar|smile|smart|sling|skype|shoes|shell|sharp|seven|sener|salon|rugby|rodeo|rocks|ricoh|reise|rehab|radio|quest|promo|prime|press|praxi|poker|place|pizza|photo|phone|party|parts|paris|osaka|omega|nowtv|nokia|ninja|nikon|nexus|movie|money|miami|media|mango|macys|lupin|lotto|lotte|locus|loans|lixil|lipsy|linde|lilly|lexus|legal|lease|lamer|kyoto|koeln|jetzt|iveco|irish|ikano|hyatt|house|horse|honda|homes|guide|gucci|group|gripe|green|gmail|globo|glass|glade|gives|gifts|games|gallo|forum|forex|final|fedex|faith|epson|email|edeka|earth|dubai|drive|delta|deals|dance|dabur|cymru|crown|codes|coach|cloud|click|citic|cisco|cheap|chase|cards|canon|build|bosch|boats|black|bingo|bible|beats|baidu|azure|autos|audio|archi|apple|amica|amfam|aetna|adult|actor|zone|zero|zara|yoga|xbox|work|wine|wiki|wien|weir|wang|voto|vote|vivo|viva|visa|vana|tube|toys|town|tips|tiaa|teva|tech|team|taxi|talk|surf|star|spot|sony|song|sohu|sncf|skin|site|sina|silk|show|shop|shia|shaw|sexy|seek|seat|scot|saxo|save|sarl|sale|safe|ruhr|rsvp|room|rmit|rich|rest|rent|reit|read|raid|qpon|prof|prod|post|porn|pohl|plus|play|pink|ping|pics|pccw|pars|page|open|ollo|nike|nico|next|news|navy|name|moto|moda|mobi|mint|mini|menu|meme|meet|maif|luxe|ltda|love|loft|loan|live|link|limo|like|life|lidl|lgbt|lego|land|kred|kpmg|kiwi|kddi|jprs|jobs|jeep|java|itau|info|immo|imdb|ieee|icbc|hsbc|host|hgtv|here|help|hdfc|haus|hair|guru|guge|goog|golf|gold|gmbh|gift|ggee|gent|gbiz|game|fund|free|ford|food|flir|fish|fire|film|fido|fiat|fast|farm|fans|fail|fage|erni|dvag|duck|docs|dish|diet|desi|dell|deal|dclk|date|data|cyou|coop|cool|club|city|citi|chat|cern|cbre|cash|case|casa|cars|care|camp|call|cafe|buzz|book|bond|bofa|blue|blog|bing|bike|best|beer|bbva|bank|band|baby|auto|audi|asia|asda|arte|arpa|army|arab|amex|ally|akdn|aero|adac|able|aarp|zip|yun|you|xyz|xxx|xin|wtf|wtc|wow|wme|win|wed|vip|vin|vig|vet|ups|uol|uno|ubs|tvs|tui|trv|top|tjx|thd|tel|tdk|tci|tax|tab|stc|srl|spa|soy|sky|ski|sfr|sex|sew|ses|scb|sca|sbs|sbi|sas|sap|rwe|run|rip|rio|ril|ren|red|qvc|pwc|pub|pru|pro|pnc|pin|pid|phd|pet|pay|ovh|ott|org|ooo|onl|ong|one|off|obi|nyc|ntt|nrw|nra|now|nhk|ngo|nfl|new|net|nec|nba|nab|mtr|mtn|msd|mov|mom|moi|moe|mma|mls|mlb|mit|mil|men|med|mba|map|man|ltd|lpl|lol|llp|llc|lds|law|lat|krd|kpn|kim|kia|kfh|joy|jot|jnj|jmp|jll|jio|jcb|itv|ist|int|ink|ing|inc|ifm|icu|ice|ibm|how|hot|hkt|hiv|hbo|gov|got|gop|goo|gmx|gmo|gle|gea|gdn|gay|gap|gal|fyi|fun|ftr|frl|fox|foo|fly|fit|fan|eus|esq|edu|eco|eat|dvr|dtv|dot|dog|dnp|diy|dhl|dev|dds|day|dad|csc|crs|cpa|com|cfd|cfa|ceo|ceb|cbs|cbn|cba|cat|car|cam|cal|cab|bzh|buy|box|bot|boo|bom|bmw|bms|biz|bio|bid|bet|bcn|bcg|bbt|bbc|bar|axa|aws|art|app|aol|anz|aig|afl|aeg|ads|aco|abc|abb|aaa|zw|zm|za|yt|ye|ws|wf|vu|vn|vi|vg|ve|vc|va|uz|uy|us|uk|ug|ua|tz|tw|tv|tt|tr|to|tn|tm|tl|tk|tj|th|tg|tf|td|tc|sz|sy|sx|sv|su|st|ss|sr|so|sn|sm|sl|sk|sj|si|sh|sg|se|sd|sc|sb|sa|rw|ru|rs|ro|re|qa|py|pw|pt|ps|pr|pn|pm|pl|pk|ph|pg|pf|pe|pa|om|nz|nu|nr|np|no|nl|ni|ng|nf|ne|nc|na|mz|my|mx|mw|mv|mu|mt|ms|mr|mq|mp|mo|mn|mm|ml|mk|mh|mg|me|md|mc|ma|ly|lv|lu|lt|ls|lr|lk|li|lc|lb|la|kz|ky|kw|kr|kp|kn|km|ki|kh|kg|ke|jp|jo|jm|je|it|is|ir|iq|io|in|im|il|ie|id|hu|ht|hr|hn|hm|hk|gy|gw|gu|gt|gs|gr|gq|gp|gn|gm|gl|gi|gh|gg|gf|ge|gd|gb|ga|fr|fo|fm|fk|fj|fi|eu|et|es|er|eg|ee|ec|dz|do|dm|dk|dj|de|cz|cy|cx|cw|cv|cu|cr|co|cn|cm|cl|ck|ci|ch|cg|cf|cd|cc|ca|bz|by|bw|bv|bt|bs|br|bo|bn|bm|bj|bi|bh|bg|bf|be|bd|bb|ba|az|ax|aw|au|at|as|ar|aq|ao|am|al|ai|ag|af|ae|ad|ac))")
url = re.compile(r"((?:https?://)?[a-zA-Z0-9\.\-_]+\.(?:travelersinsurance|northwesternmutual|sandvikcoromant|kerryproperties|americanexpress|weatherchannel|kerrylogistics|cookingchannel|cancerresearch|bananarepublic|americanfamily|afamilycompany|wolterskluwer|travelchannel|spreadbetting|lifeinsurance|international|versicherung|scholarships|lplfinancial|construction|williamhill|redumbrella|progressive|productions|playstation|photography|olayangroup|motorcycles|lamborghini|kerryhotels|investments|foodnetwork|enterprises|engineering|creditunion|contractors|calvinklein|bridgestone|blockbuster|blackfriday|barclaycard|accountants|volkswagen|vlaanderen|university|technology|tatamotors|swiftcover|schaeffler|restaurant|republican|realestate|prudential|protection|properties|onyourside|nextdirect|newholland|nationwide|mitsubishi|management|industries|immobilien|healthcare|foundation|extraspace|eurovision|cuisinella|creditcard|consulting|capitalone|boehringer|bnpparibas|basketball|associates|apartments|accountant|yodobashi|vacations|travelers|stockholm|statefarm|statebank|solutions|shangrila|scjohnson|richardli|pramerica|passagens|panasonic|microsoft|melbourne|marshalls|marketing|lifestyle|landrover|lancaster|kuokgroup|insurance|institute|homesense|homegoods|homedepot|hisamitsu|goldpoint|furniture|fujixerox|frontdoor|fresenius|firestone|financial|fairwinds|equipment|education|directory|community|christmas|bloomberg|barcelona|aquarelle|analytics|amsterdam|allfinanz|alfaromeo|accenture|yokohama|woodside|verisign|ventures|vanguard|training|supplies|stcgroup|software|softbank|showtime|shopping|services|security|samsclub|saarland|reliance|redstone|property|plumbing|pictures|pharmacy|partners|observer|mortgage|merckmsd|memorial|mckinsey|maserati|marriott|lundbeck|lighting|jpmorgan|istanbul|ipiranga|infiniti|hospital|holdings|helsinki|hdfcbank|guardian|graphics|grainger|goodyear|frontier|football|firmdale|fidelity|feedback|exchange|etisalat|ericsson|engineer|download|discover|discount|diamonds|democrat|deloitte|delivery|computer|commbank|clothing|clinique|cleaning|cityeats|cipriani|catholic|catering|capetown|business|builders|budapest|brussels|broadway|bradesco|boutique|baseball|bargains|barefoot|barclays|attorney|allstate|airforce|abudhabi|zuerich|youtube|yamaxun|xfinity|winners|windows|whoswho|wedding|website|weather|watches|wanggou|walmart|trading|toshiba|tiffany|tickets|theatre|theater|temasek|systems|surgery|support|storage|staples|singles|shriram|shiksha|science|schwarz|schmidt|sandvik|samsung|rexroth|reviews|rentals|recipes|realtor|politie|pioneer|philips|origins|organic|oldnavy|okinawa|neustar|network|netflix|netbank|monster|markets|lincoln|limited|leclerc|latrobe|lasalle|lanxess|lacaixa|komatsu|kitchen|juniper|jewelry|ismaili|hyundai|hotmail|hoteles|hosting|holiday|hitachi|hangout|hamburg|guitars|grocery|godaddy|genting|gallery|fujitsu|frogans|forsale|flowers|florist|flights|fitness|fishing|finance|ferrero|ferrari|fashion|farmers|express|exposed|domains|digital|dentist|cruises|cricket|courses|coupons|country|corsica|cooking|contact|compare|company|comcast|cologne|college|clubmed|citadel|chintai|charity|channel|careers|caravan|capital|bugatti|brother|booking|bestbuy|bentley|bauhaus|banamex|avianca|auspost|audible|auction|athleta|android|alibaba|agakhan|academy|abogado|zappos|yandex|yachts|xihuan|webcam|walter|vuelos|voyage|voting|vision|virgin|villas|viking|viajes|unicom|travel|toyota|tkmaxx|tjmaxx|tienda|tennis|tattoo|target|taobao|taipei|sydney|swatch|suzuki|supply|studio|stream|social|soccer|shouji|select|secure|search|schule|school|sanofi|sakura|safety|ryukyu|rogers|rocher|review|report|repair|reisen|realty|racing|quebec|pictet|physio|photos|pfizer|otsuka|orange|oracle|online|olayan|office|nowruz|norton|nissay|nissan|natura|nagoya|mutual|museum|moscow|mormon|monash|mobile|mattel|market|makeup|maison|madrid|luxury|london|locker|living|lefrak|lawyer|latino|lancia|kosher|kindle|kinder|kaufen|juegos|joburg|jaguar|intuit|insure|imamat|hughes|hotels|hockey|hiphop|hermes|health|gratis|google|global|giving|george|garden|gallup|futbol|flickr|family|expert|events|estate|energy|emerck|durban|dupont|dunlop|doctor|direct|design|dental|degree|dealer|datsun|dating|cruise|credit|coupon|condos|comsec|coffee|clinic|claims|circle|church|chrome|chanel|center|casino|caseih|career|camera|broker|boston|bostik|bharti|berlin|beauty|bayern|author|aramco|anquan|amazon|alstom|alsace|alipay|airtel|airbus|agency|africa|abbvie|abbott|abarth|yahoo|xerox|world|works|weibo|weber|watch|wales|volvo|vodka|video|vegas|ubank|tushu|tunes|trust|trade|tours|total|toray|tools|tokyo|today|tmall|tirol|tires|tatar|swiss|sucks|style|study|store|stada|sport|space|solar|smile|smart|sling|skype|shoes|shell|sharp|seven|sener|salon|rugby|rodeo|rocks|ricoh|reise|rehab|radio|quest|promo|prime|press|praxi|poker|place|pizza|photo|phone|party|parts|paris|osaka|omega|nowtv|nokia|ninja|nikon|nexus|movie|money|miami|media|mango|macys|lupin|lotto|lotte|locus|loans|lixil|lipsy|linde|lilly|lexus|legal|lease|lamer|kyoto|koeln|jetzt|iveco|irish|ikano|hyatt|house|horse|honda|homes|guide|gucci|group|gripe|green|gmail|globo|glass|glade|gives|gifts|games|gallo|forum|forex|final|fedex|faith|epson|email|edeka|earth|dubai|drive|delta|deals|dance|dabur|cymru|crown|codes|coach|cloud|click|citic|cisco|cheap|chase|cards|canon|build|bosch|boats|black|bingo|bible|beats|baidu|azure|autos|audio|archi|apple|amica|amfam|aetna|adult|actor|zone|zero|zara|yoga|xbox|work|wine|wiki|wien|weir|wang|voto|vote|vivo|viva|visa|vana|tube|toys|town|tips|tiaa|teva|tech|team|taxi|talk|surf|star|spot|sony|song|sohu|sncf|skin|site|sina|silk|show|shop|shia|shaw|sexy|seek|seat|scot|saxo|save|sarl|sale|safe|ruhr|rsvp|room|rmit|rich|rest|rent|reit|read|raid|qpon|prof|prod|post|porn|pohl|plus|play|pink|ping|pics|pccw|pars|page|open|ollo|nike|nico|next|news|navy|name|moto|moda|mobi|mint|mini|menu|meme|meet|maif|luxe|ltda|love|loft|loan|live|link|limo|like|life|lidl|lgbt|lego|land|kred|kpmg|kiwi|kddi|jprs|jobs|jeep|java|itau|info|immo|imdb|ieee|icbc|hsbc|host|hgtv|here|help|hdfc|haus|hair|guru|guge|goog|golf|gold|gmbh|gift|ggee|gent|gbiz|game|fund|free|ford|food|flir|fish|fire|film|fido|fiat|fast|farm|fans|fail|fage|erni|dvag|duck|docs|dish|diet|desi|dell|deal|dclk|date|data|cyou|coop|cool|club|city|citi|chat|cern|cbre|cash|case|casa|cars|care|camp|call|cafe|buzz|book|bond|bofa|blue|blog|bing|bike|best|beer|bbva|bank|band|baby|auto|audi|asia|asda|arte|arpa|army|arab|amex|ally|akdn|aero|adac|able|aarp|zip|yun|you|xyz|xxx|xin|wtf|wtc|wow|wme|win|wed|vip|vin|vig|vet|ups|uol|uno|ubs|tvs|tui|trv|top|tjx|thd|tel|tdk|tci|tax|tab|stc|srl|spa|soy|sky|ski|sfr|sex|sew|ses|scb|sca|sbs|sbi|sas|sap|rwe|run|rip|rio|ril|ren|red|qvc|pwc|pub|pru|pro|pnc|pin|pid|phd|pet|pay|ovh|ott|org|ooo|onl|ong|one|off|obi|nyc|ntt|nrw|nra|now|nhk|ngo|nfl|new|net|nec|nba|nab|mtr|mtn|msd|mov|mom|moi|moe|mma|mls|mlb|mit|mil|men|med|mba|map|man|ltd|lpl|lol|llp|llc|lds|law|lat|krd|kpn|kim|kia|kfh|joy|jot|jnj|jmp|jll|jio|jcb|itv|ist|int|ink|ing|inc|ifm|icu|ice|ibm|how|hot|hkt|hiv|hbo|gov|got|gop|goo|gmx|gmo|gle|gea|gdn|gay|gap|gal|fyi|fun|ftr|frl|fox|foo|fly|fit|fan|eus|esq|edu|eco|eat|dvr|dtv|dot|dog|dnp|diy|dhl|dev|dds|day|dad|csc|crs|cpa|com|cfd|cfa|ceo|ceb|cbs|cbn|cba|cat|car|cam|cal|cab|bzh|buy|box|bot|boo|bom|bmw|bms|biz|bio|bid|bet|bcn|bcg|bbt|bbc|bar|axa|aws|art|app|aol|anz|aig|afl|aeg|ads|aco|abc|abb|aaa|zw|zm|za|yt|ye|ws|wf|vu|vn|vi|vg|ve|vc|va|uz|uy|us|uk|ug|ua|tz|tw|tv|tt|tr|to|tn|tm|tl|tk|tj|th|tg|tf|td|tc|sz|sy|sx|sv|su|st|ss|sr|so|sn|sm|sl|sk|sj|si|sh|sg|se|sd|sc|sb|sa|rw|ru|rs|ro|re|qa|py|pw|pt|ps|pr|pn|pm|pl|pk|ph|pg|pf|pe|pa|om|nz|nu|nr|np|no|nl|ni|ng|nf|ne|nc|na|mz|my|mx|mw|mv|mu|mt|ms|mr|mq|mp|mo|mn|mm|ml|mk|mh|mg|me|md|mc|ma|ly|lv|lu|lt|ls|lr|lk|li|lc|lb|la|kz|ky|kw|kr|kp|kn|km|ki|kh|kg|ke|jp|jo|jm|je|it|is|ir|iq|io|in|im|il|ie|id|hu|ht|hr|hn|hm|hk|gy|gw|gu|gt|gs|gr|gq|gp|gn|gm|gl|gi|gh|gg|gf|ge|gd|gb|ga|fr|fo|fm|fk|fj|fi|eu|et|es|er|eg|ee|ec|dz|do|dm|dk|dj|de|cz|cy|cx|cw|cv|cu|cr|co|cn|cm|cl|ck|ci|ch|cg|cf|cd|cc|ca|bz|by|bw|bv|bt|bs|br|bo|bn|bm|bj|bi|bh|bg|bf|be|bd|bb|ba|az|ax|aw|au|at|as|ar|aq|ao|am|al|ai|ag|af|ae|ad|ac))")
username = re.compile(r"(@[a-zA-Z0-9\.\-_]+[a-zA-Z0-9]+)")

## N.B. - this list of moji *must* be in reverse order of length (i.e., longest moji come first)
moji_list = ["┻━┻︵ヽ('Д')ﾉ︵┻━┻", "v(^_^)v（'-'*)", ".....φ(・∀・＊)", "┬──┬ ¯\\_(ツ)", "(ノಠ益ಠ)ノ彡┻━┻", "(╯°□°）╯︵┻━┻", "((d[-_-]b))", "( ͡° ͜ʖ ͡°)", "┬─┬ノ(º_ºノ)", "(*^^)v(^^)", "(-.-)y-°°°", "(^.^)y-.o○", "(^^ゞ(^_^;)", "zzz(︶｡︶✽)", "(*^3^)/~☆", "¯\\_(ツ)_/¯", "(V)o￥o(V)", "(ToT)/~~~", "(T_T)/~~~", "(@^^)/~~~", "($··)/~~~", "(-_-)/~~~", "(^.^)/~~~", "(;_;)/~~~", "V=(° °)=V", "⎛⎝(•ⱅ•)⎠⎞", "@}-;-'---", "(*°∀°)=3", "(^^)/~~~", "(=^・・^=)", "<m(__)m>", "(-_-)zzz", "(=ʘᆽʘ=)∫", "～°·_·°～", "~>°)～～～", "<*))>=<", "<+))><<", ">°))))彡", "('･ω･')", "ヽ('ー｀)┌", "(*'▽｀*)", "(*^▽^*)", "(^)o(^)", "(●^o^●)", "(^0_0^)", "＼(◎o◎)／", "(*^0^*)", "ヽ(^o^)丿", "ヽ(^。^)ノ", "＼(-o-)／", "＼(^o^)／", "＼(~o~)／", "(^_^)/~", "(*^.^*)", "（*^_^*）", "(=^・^=)", "<(_ _)>", "_(_^_)_", "_(._.)_", "∩(·ω·)∩", "(/◕ヮ◕)/", "<(｀^')>", "((+_+))", "(^_-)-☆", "(#^.^#)", "><(((*>", "<*)))-{", "@>-->--", ":-###..", "<°)))彡", "(°))<<", ">°)))彡", "(*￣m￣)", "(￣□￣;)", "(✿◠‿◠)", "(~_~メ)", "(-_-メ)", "(^_^メ)", "!(^^)!", "(＠_＠;)", "(^_^.)", "(；一_一)", "(／ロ°)／", "＼(°ロ＼)", "m(__)m", "(^o^)丿", "(≧∇≦)/", "(^o^)／", "(^O^)／", "(^_^)/", "(°_°>)", "(・_・;)", "(・.・;)", "(~_~;)", "(-_-;)", "(>_<)>", "8====D", "@}->--", ":###..", ">°))彡", "('A')", "(°◇°)", "（ﾟДﾟ)", "(o.o)", "(￣ー￣)", ")^o^(", "(^○^)", "(^o^)", "(^O^)", "(^◇^)", "(^ｕ^)", "φ(..)", "(..)φ", "(ーー;)", "<'ヘ'>", "<'～'>", "(・へ・)", "(－－〆)", "(ーー゛)", "(- -)", "(p_-)", "(~_~)", "(~o~)", "('∀')", "(・∀・)", "(^▽^)", "(^ｖ^)", "(@_@。", "(@_@)", "(+_+)", "(*_*;", "(*_*)", "（^-^)", "(^J^)", "(^_^)", "(^·^)", "(^ム^)", "(^.^)", "(^<^)", "§^.^§", "<^!^>", ">^_^<", "(?_?)", "(._.)", "=^_^=", "(=_=)", "(-_-)", "(-.-)", "(ー_ー)", "(Ｔ▽Ｔ)", "(ToT)", "(:_;)", "(;O;)", "(;_:)", "(;_;)", "(T_T)", "(/_;)", "('_')", "(·ω·)", "(^^)/", "(°o°)", "(°レ°)", "(°_°)", "(°.°)", "(°-°)", "(+o+)", "(^_-)", "(^^;)", "(・・;)", "(';')", "(>_<)", "V.v.V", "*\\0/*", "8===D", "><ヨヨ", "(｀')", "(^^ゞ", "(⌒▽⌒", "(^^)", "(－ლ)", "(・・?", "(..)", "(一一)", "(__)", "(°°)", "^_^;", "^<_<", ">_>^", "o/\\o", "@};-", "<:-'", "3:-)", "}:-)", ">:-)", "0;^)", "0:-)", "0:-3", "O:-)", "://3", "://)", "D-':", ":'-)", ":'-(", ":-))", "●～*", "UwU", "uwu", "o.O", "o_0", "°O°", "°o°", "^/^", "^m^", ";n;", ";-;", ";_;", "_)m", "m(_", "^ω^", "^_^", "^^;", ">.<", "O-O", "o_o", "o_O", "O_o", "o-o", "O_O", "v.v", "><>", "<\\3", "</3", "x=3", "x-3", "8=X", "8-X", ">.>", "<.<", ">_>", "<_<", ":-l", ":-'", "%-)", "#-)", ":-J", "B-)", ">:3", ">;)", "3:)", "}:)", "0:)", "0:3", "O:)", ":-&", ":-#", ":-X", ">:/", ">:\\", ":-.", ":-/", ">:P", ":-b", ":-þ", ":-Þ", ":-p", "x-p", "X-P", ":-P", ":-,", ";^)", ";-]", "*-)", ";-)", ":-*", ">:O", "8-0", ":-0", ":-o", ":-O", "D:<", ":'(", ":-[", ":-<", ":-c", ":-(", "B-D", "B'D", "B^D", "X-D", "x-D", "8-D", ":-D", ":^)", ":c)", ":o)", ":-}", "8')", "8-)", ":'>", ":->", ":-3", ":-]", ":')", ":-)", "o7", "<3", "*<", ":E", "%)", ";3", ":&", ":#", ":X", ":$", ":-", ":S", "=L", ":L", "=\\", "=/", ":\\", ":/", "=p", "d:", ":b", ":þ", ":Þ", ":p", "xp", "XP", ":P", ";D", ";>", ";]", "*)", ";)", ":×", ":*", ":o", ":O", "DX", "D=", "D;", "D8", "D:", ";(", ":@", ":{", ":[", ":<", ":c", ":(", "C:", "c:", "=3", "=D", "XD", "xD", "8D", ":D", "=)", "=]", ":}", "8)", ":>", ":3", ":]", ":)"]
moji_regex = re.compile(r"(?<![A-Za-z])(┻━┻︵ヽ\('Д'\)ﾉ︵┻━┻|v\(\^_\^\)|v（'\-'\*\)|\.\.\.\.\.φ\(・∀・＊\)|┬──┬¯\\_\(ツ\)|\(ノಠ益ಠ\)ノ彡┻━┻|\(╯°□°）╯︵┻━┻|\(\(d\[\-_\-\]b\)\)|┬─┬ノ\(º_ºノ\)|\(\*\^\^\)v\(\^\^\)|\(\-\.\-\)y\-°°°|\(\^\.\^\)y\-\.o○|\(\^\^ゞ\(\^_\^;\)|zzz\(︶｡︶✽\)|\(\*\^3\^\)/~☆|¯\\_\(ツ\)_/¯|\(V\)o￥o\(V\)|\(ToT\)/~~~|\(T_T\)/~~~|\(@\^\^\)/~~~|\(\$··\)/~~~|\(\-_\-\)/~~~|\(\^\.\^\)/~~~|\(;_;\)/~~~|V=\(° °\)=V|⎛⎝\(•ⱅ•\)⎠⎞|@\}-;-'---|\(\*°∀°\)=3|\(\^\^\)/~~~|\(=\^・・\^=\)|<m\(__\)m>|\(\-_\-\)zzz|\(=ʘᆽʘ=\)∫|～°·_·°～|~>°\)～～～|<\*\)\)>=<|<\+\)\)><<|>°\)\)\)\)彡|\('･ω･'\)|ヽ\('ー｀\)┌|\(\*'▽｀\*\)|\(\*\^▽\^\*\)|\(\^\)o\(\^\)|\(●\^o\^●\)|\(\^0_0\^\)|＼\(◎o◎\)／|\(\*\^0\^\*\)|ヽ\(\^o\^\)丿|ヽ\(\^。\^\)ノ|＼\(\-o\-\)／|＼\(\^o\^\)／|＼\(~o~\)／|\(\^_\^\)/~|\(\*\^\.\^\*\)|（\*\^_\^\*）|\(=\^・\^=\)|<\(__\)>|_\(_\^_\)_|_\(\._\.\)_|∩\(·ω·\)∩|\(/◕ヮ◕\)/|<\(｀\^'\)>|\(\(\+_\+\)\)|\(\^_\-\)\-☆|\(#\^\.\^#\)|><\(\(\(\*>|<\*\)\)\)-\{|@>-->--|:-###\.\.|<°\)\)\)彡|\(°\)\)<<|>°\)\)\)彡|\(\*￣m￣\)|\(￣□￣;\)|\(✿◠‿◠\)|\(~_~メ\)|\(\-_\-メ\)|\(\^_\^メ\)|!\(\^\^\)!|\(＠_＠;\)|\(\^_\^\.\)|\(；一_一\)|\(／ロ°\)／|＼\(°ロ＼\)|m\(__\)m|\(\^o\^\)丿|\(≧∇≦\)/|\(\^o\^\)／|\(\^O\^\)／|\(\^_\^\)/|\(°_°>\)|\(・_・;\)|\(・\.・;\)|\(~_~;\)|\(\-_\-;\)|\(>_<\)>|8====D|@\}\->\-\-|:###\.\.|>°\)\)彡|\('A'\)|\(°◇°\)|（ﾟДﾟ\)|\(o\.o\)|\(￣ー￣\)|\)\^o\^\(|\(\^○\^\)|\(\^o\^\)|\(\^O\^\)|\(\^◇\^\)|\(\^ｕ\^\)|φ\(\.\.\)|\(\.\.\)φ|\(ーー;\)|<'ヘ'>|<'～'>|\(・へ・\)|\(－－〆\)|\(ーー゛\)|\(\- \-\)|\(p_\-\)|\(~_~\)|\(~o~\)|\('∀'\)|\(・∀・\)|\(\^▽\^\)|\(\^ｖ\^\)|\(@_@。|\(@_@\)|\(\+_\+\)|\(\*_\*;|\(\*_\*\)|（\^-\^\)|\(\^J\^\)|\(\^_\^\)|\(\^·\^\)|\(\^ム\^\)|\(\^\.\^\)|\(\^<\^\)|§\^\.\^§|<\^!\^>|>\^_\^<|\(\?_\?\)|\(\._\.\)|=\^_\^=|\(=_=\)|\(\-_\-\)|\(\-\.\-\)|\(ー_ー\)|\(Ｔ▽Ｔ\)|\(ToT\)|\(:_;\)|\(;O;\)|\(;_:\)|\(;_;\)|\(T_T\)|\(/_;\)|\('_'\)|\(·ω·\)|\(\^\^\)/|\(°o°\)|\(°レ°\)|\(°_°\)|\(°\.°\)|\(°\-°\)|\(\+o\+\)|\(\^_\-\)|\(\^\^;\)|\(・・;\)|\(';'\)|\(>_<\)|V\.v\.V|\*\\0/\*|8===D|><ヨヨ|\(｀'\)|\(\^\^ゞ|\(⌒▽⌒|\(\^\^\)|\(－ლ\)|\(・・\?|\(\.\.\)|\(一一\)|\(__\)|\(°°\)|\^_\^;|\^<_<|>_>\^|o/\\o|@\};\-|<:-'|3:-\)|\}:-\)|>:-\)|0;\^\)|0:-\)|0:-3|O:-\)|://3|://\)|D-':|:'-\)|:'-\(|:\-\)\)|●～\*|UwU|uwu|o\.O|o_0|°O°|°o°|\^/\^|\^m\^|;n;|;\-;|;_;|_\)m|m\(_|\^ω\^|\^_\^|\^\^;|>\.<|O\-O|o_o|o_O|O_o|o-o|O_O|v\.v|><>|<\\3|</3|x=3|x\-3|8=X|8\-X|>\.>|<\.<|>_>|<_<|:\-l|:\-'|%-\)|#-\)|:-J|B\-\)|>:3|>;\)|3:\)|\}:\)|0:\)|0:3|O:\)|:-&|:-#|:-X|>:/|>:\\|:-\.|:\-/|>:P|:-b|:-þ|:-Þ|:-p|x-p|X-P|:-P|:-,|;\^\)|;-\]|\*\-\)|;-\)|:\-\*|>:O|8-0|:\-0|:-o|:-O|:-0|D:<|:'\(|:-\[|:-<|:-c|:-\(|:\-\||B\-D|B'D|B\^D|X-D|x-D|8-D|:-D|:\^\)|:c\)|:o\)|:\-\}|8'\)|8\-\)|:'>|:\->|:\-3|:\-\]|:'\)|:-\)|o7|<3|\*<|:E|%\)|;3|:&|:#|:X|:\$|:-|:S|=L|:L|=\\|=/|:\\|:/|=p|d:|:b|:þ|:Þ|:p|xp|XP|:P|;D|;>|;\]|\*\)|;\)|:×|:\*|:o|:O|:0|DX|D=|D;|D8|D:|;\(|:@|:\{|:\[|:<|:c|:\(|C:|c:|=3|=D|XD|xD|8D|:D|=\)|=\]|:\}|8\)|:>|:3|:\]|:\)|:\|)(?![A-Za-z])")
